
services:
  api:
    build: ./api
    command: npm start
    ports:
      - '3001:3000'
    volumes:
      - ./api:/app
      - /app/node_modules   # node_modules をコンテナ内に保持
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'

  front:
    build: ./front
    volumes:
      - ./front:/app
      - node_modules:/app/node_modules
    ports:
      - '8080:8080'
    tty: true
    stdin_open: true
    command: npm run serve

volumes:
  mysql_data:
  node_modules:
