"use strict";
exports.__esModule = true;
exports.itemsRouter = void 0;
var GetItemsController_1 = require("./controllers/GetItemsController");
var GetItemsInteractor_1 = require("./interactors/GetItemsInteractor");
var ItemRepository_1 = require("./infrastructures/repositories/ItemRepository");
var client_1 = require("@prisma/client");
var express_1 = require("express");
var itemsRouter = express_1["default"].Router();
exports.itemsRouter = itemsRouter;
var prisma = new client_1.PrismaClient();
var itemRepository = new ItemRepository_1.ItemRepository(prisma);
var getItemsInteractor = new GetItemsInteractor_1.GetItemsInteractor(itemRepository);
var getItemsController = new GetItemsController_1.GetItemsController(getItemsInteractor);
itemsRouter.get("/", getItemsController.execute.bind(getItemsController));
